countries = [
	{
		"alpha2": "AD",
		"alpha3": "AND",
		"numeric": "20",
		"fips": "AN",
		"Country": "Andorra",
		"Capital": "Andorra la Vella",
		"Area in km²": "468",
		"Population": "84000",
		"Continent": "EU"
	},
	{
		"alpha2": "AE",
		"alpha3": "ARE",
		"numeric": "784",
		"fips": "AE",
		"Country": "United Arab Emirates",
		"Capital": "Abu Dhabi",
		"Area in km²": "82880",
		"Population": "4975593",
		"Continent": "AS"
	},
	{
		"alpha2": "AF",
		"alpha3": "AFG",
		"numeric": "4",
		"fips": "AF",
		"Country": "Afghanistan",
		"Capital": "Kabul",
		"Area in km²": "647500",
		"Population": "29121286",
		"Continent": "AS"
	},
	{
		"alpha2": "AG",
		"alpha3": "ATG",
		"numeric": "28",
		"fips": "AC",
		"Country": "Antigua and Barbuda",
		"Capital": "St. John's",
		"Area in km²": "443",
		"Population": "86754",
		"Continent": "NA"
	},
	{
		"alpha2": "AI",
		"alpha3": "AIA",
		"numeric": "660",
		"fips": "AV",
		"Country": "Anguilla",
		"Capital": "The Valley",
		"Area in km²": "102",
		"Population": "13254",
		"Continent": "NA"
	},
	{
		"alpha2": "AL",
		"alpha3": "ALB",
		"numeric": "8",
		"fips": "AL",
		"Country": "Albania",
		"Capital": "Tirana",
		"Area in km²": "28748",
		"Population": "2986952",
		"Continent": "EU"
	},
	{
		"alpha2": "AM",
		"alpha3": "ARM",
		"numeric": "51",
		"fips": "AM",
		"Country": "Armenia",
		"Capital": "Yerevan",
		"Area in km²": "29800",
		"Population": "2968000",
		"Continent": "AS"
	},
	{
		"alpha2": "AN",
		"alpha3": "ANT",
		"numeric": "530",
		"fips": "NT",
		"Country": "",
		"Capital": "Willemstad",
		"Area in km²": "960",
		"Population": "136197",
		"Continent": "NA"
	},
	{
		"alpha2": "AO",
		"alpha3": "AGO",
		"numeric": "24",
		"fips": "AO",
		"Country": "Angola",
		"Capital": "Luanda",
		"Area in km²": "1246700",
		"Population": "13068161",
		"Continent": "AF"
	},
	{
		"alpha2": "AQ",
		"alpha3": "ATA",
		"numeric": "10",
		"fips": "AY",
		"Country": "Antarctica",
		"Capital": "",
		"Area in km²": "14000000",
		"Population": "0",
		"Continent": "AN"
	},
	{
		"alpha2": "AR",
		"alpha3": "ARG",
		"numeric": "32",
		"fips": "AR",
		"Country": "Argentina",
		"Capital": "Buenos Aires",
		"Area in km²": "2766890",
		"Population": "41343201",
		"Continent": "SA"
	},
	{
		"alpha2": "AS",
		"alpha3": "ASM",
		"numeric": "16",
		"fips": "AQ",
		"Country": "American Samoa",
		"Capital": "Pago Pago",
		"Area in km²": "199",
		"Population": "57881",
		"Continent": "OC"
	},
	{
		"alpha2": "AT",
		"alpha3": "AUT",
		"numeric": "40",
		"fips": "AU",
		"Country": "Austria",
		"Capital": "Vienna",
		"Area in km²": "83858",
		"Population": "8205000",
		"Continent": "EU"
	},
	{
		"alpha2": "AU",
		"alpha3": "AUS",
		"numeric": "36",
		"fips": "AS",
		"Country": "Australia",
		"Capital": "Canberra",
		"Area in km²": "7686850",
		"Population": "21515754",
		"Continent": "OC"
	},
	{
		"alpha2": "AW",
		"alpha3": "ABW",
		"numeric": "533",
		"fips": "AA",
		"Country": "Aruba",
		"Capital": "Oranjestad",
		"Area in km²": "193",
		"Population": "71566",
		"Continent": "NA"
	},
	{
		"alpha2": "AX",
		"alpha3": "ALA",
		"numeric": "248",
		"fips": "",
		"Country": "Åland",
		"Capital": "Mariehamn",
		"Area in km²": "",
		"Population": "26711",
		"Continent": "EU"
	},
	{
		"alpha2": "AZ",
		"alpha3": "AZE",
		"numeric": "31",
		"fips": "AJ",
		"Country": "Azerbaijan",
		"Capital": "Baku",
		"Area in km²": "86600",
		"Population": "8303512",
		"Continent": "AS"
	},
	{
		"alpha2": "BA",
		"alpha3": "BIH",
		"numeric": "70",
		"fips": "BK",
		"Country": "Bosnia and Herzegovina",
		"Capital": "Sarajevo",
		"Area in km²": "51129",
		"Population": "4590000",
		"Continent": "EU"
	},
	{
		"alpha2": "BB",
		"alpha3": "BRB",
		"numeric": "52",
		"fips": "BB",
		"Country": "Barbados",
		"Capital": "Bridgetown",
		"Area in km²": "431",
		"Population": "285653",
		"Continent": "NA"
	},
	{
		"alpha2": "BD",
		"alpha3": "BGD",
		"numeric": "50",
		"fips": "BG",
		"Country": "Bangladesh",
		"Capital": "Dhaka",
		"Area in km²": "144000",
		"Population": "156118464",
		"Continent": "AS"
	},
	{
		"alpha2": "BE",
		"alpha3": "BEL",
		"numeric": "56",
		"fips": "BE",
		"Country": "Belgium",
		"Capital": "Brussels",
		"Area in km²": "30510",
		"Population": "10403000",
		"Continent": "EU"
	},
	{
		"alpha2": "BF",
		"alpha3": "BFA",
		"numeric": "854",
		"fips": "UV",
		"Country": "Burkina Faso",
		"Capital": "Ouagadougou",
		"Area in km²": "274200",
		"Population": "16241811",
		"Continent": "AF"
	},
	{
		"alpha2": "BG",
		"alpha3": "BGR",
		"numeric": "100",
		"fips": "BU",
		"Country": "Bulgaria",
		"Capital": "Sofia",
		"Area in km²": "110910",
		"Population": "7148785",
		"Continent": "EU"
	},
	{
		"alpha2": "BH",
		"alpha3": "BHR",
		"numeric": "48",
		"fips": "BA",
		"Country": "Bahrain",
		"Capital": "Manama",
		"Area in km²": "665",
		"Population": "738004",
		"Continent": "AS"
	},
	{
		"alpha2": "BI",
		"alpha3": "BDI",
		"numeric": "108",
		"fips": "BY",
		"Country": "Burundi",
		"Capital": "Bujumbura",
		"Area in km²": "27830",
		"Population": "9863117",
		"Continent": "AF"
	},
	{
		"alpha2": "BJ",
		"alpha3": "BEN",
		"numeric": "204",
		"fips": "BN",
		"Country": "Benin",
		"Capital": "Porto-Novo",
		"Area in km²": "112620",
		"Population": "9056010",
		"Continent": "AF"
	},
	{
		"alpha2": "BL",
		"alpha3": "BLM",
		"numeric": "652",
		"fips": "TB",
		"Country": "Saint Barthélemy",
		"Capital": "Gustavia",
		"Area in km²": "21",
		"Population": "8450",
		"Continent": "NA"
	},
	{
		"alpha2": "BM",
		"alpha3": "BMU",
		"numeric": "60",
		"fips": "BD",
		"Country": "Bermuda",
		"Capital": "Hamilton",
		"Area in km²": "53",
		"Population": "65365",
		"Continent": "NA"
	},
	{
		"alpha2": "BN",
		"alpha3": "BRN",
		"numeric": "96",
		"fips": "BX",
		"Country": "Brunei",
		"Capital": "Bandar Seri Begawan",
		"Area in km²": "5770",
		"Population": "395027",
		"Continent": "AS"
	},
	{
		"alpha2": "BO",
		"alpha3": "BOL",
		"numeric": "68",
		"fips": "BL",
		"Country": "Bolivia",
		"Capital": "Sucre",
		"Area in km²": "1098580",
		"Population": "9947418",
		"Continent": "SA"
	},
	{
		"alpha2": "BQ",
		"alpha3": "BES",
		"numeric": "535",
		"fips": "",
		"Country": "Bonaire",
		"Capital": "",
		"Area in km²": "",
		"Population": "18012",
		"Continent": "NA"
	},
	{
		"alpha2": "BR",
		"alpha3": "BRA",
		"numeric": "76",
		"fips": "BR",
		"Country": "Brazil",
		"Capital": "Brasilia",
		"Area in km²": "8511965",
		"Population": "201103330",
		"Continent": "SA"
	},
	{
		"alpha2": "BS",
		"alpha3": "BHS",
		"numeric": "44",
		"fips": "BF",
		"Country": "Bahamas",
		"Capital": "Nassau",
		"Area in km²": "13940",
		"Population": "301790",
		"Continent": "NA"
	},
	{
		"alpha2": "BT",
		"alpha3": "BTN",
		"numeric": "64",
		"fips": "BT",
		"Country": "Bhutan",
		"Capital": "Thimphu",
		"Area in km²": "47000",
		"Population": "699847",
		"Continent": "AS"
	},
	{
		"alpha2": "BV",
		"alpha3": "BVT",
		"numeric": "74",
		"fips": "BV",
		"Country": "Bouvet Island",
		"Capital": "",
		"Area in km²": "",
		"Population": "0",
		"Continent": "AN"
	},
	{
		"alpha2": "BW",
		"alpha3": "BWA",
		"numeric": "72",
		"fips": "BC",
		"Country": "Botswana",
		"Capital": "Gaborone",
		"Area in km²": "600370",
		"Population": "2029307",
		"Continent": "AF"
	},
	{
		"alpha2": "BY",
		"alpha3": "BLR",
		"numeric": "112",
		"fips": "BO",
		"Country": "Belarus",
		"Capital": "Minsk",
		"Area in km²": "207600",
		"Population": "9685000",
		"Continent": "EU"
	},
	{
		"alpha2": "BZ",
		"alpha3": "BLZ",
		"numeric": "84",
		"fips": "BH",
		"Country": "Belize",
		"Capital": "Belmopan",
		"Area in km²": "22966",
		"Population": "314522",
		"Continent": "NA"
	},
	{
		"alpha2": "CA",
		"alpha3": "CAN",
		"numeric": "124",
		"fips": "CA",
		"Country": "Canada",
		"Capital": "Ottawa",
		"Area in km²": "9984670",
		"Population": "33679000",
		"Continent": "NA"
	},
	{
		"alpha2": "CC",
		"alpha3": "CCK",
		"numeric": "166",
		"fips": "CK",
		"Country": "Cocos [Keeling] Islands",
		"Capital": "West Island",
		"Area in km²": "14",
		"Population": "628",
		"Continent": "AS"
	},
	{
		"alpha2": "CD",
		"alpha3": "COD",
		"numeric": "180",
		"fips": "CG",
		"Country": "Congo",
		"Capital": "Kinshasa",
		"Area in km²": "2345410",
		"Population": "70916439",
		"Continent": "AF"
	},
	{
		"alpha2": "CF",
		"alpha3": "CAF",
		"numeric": "140",
		"fips": "CT",
		"Country": "Central African Republic",
		"Capital": "Bangui",
		"Area in km²": "622984",
		"Population": "4844927",
		"Continent": "AF"
	},
	{
		"alpha2": "CG",
		"alpha3": "COG",
		"numeric": "178",
		"fips": "CF",
		"Country": "Republic of the Congo",
		"Capital": "Brazzaville",
		"Area in km²": "342000",
		"Population": "3039126",
		"Continent": "AF"
	},
	{
		"alpha2": "CH",
		"alpha3": "CHE",
		"numeric": "756",
		"fips": "SZ",
		"Country": "Switzerland",
		"Capital": "Berne",
		"Area in km²": "41290",
		"Population": "7581000",
		"Continent": "EU"
	},
	{
		"alpha2": "CI",
		"alpha3": "CIV",
		"numeric": "384",
		"fips": "IV",
		"Country": "Ivory Coast",
		"Capital": "Yamoussoukro",
		"Area in km²": "322460",
		"Population": "21058798",
		"Continent": "AF"
	},
	{
		"alpha2": "CK",
		"alpha3": "COK",
		"numeric": "184",
		"fips": "CW",
		"Country": "Cook Islands",
		"Capital": "Avarua",
		"Area in km²": "240",
		"Population": "21388",
		"Continent": "OC"
	},
	{
		"alpha2": "CL",
		"alpha3": "CHL",
		"numeric": "152",
		"fips": "CI",
		"Country": "Chile",
		"Capital": "Santiago",
		"Area in km²": "756950",
		"Population": "16746491",
		"Continent": "SA"
	},
	{
		"alpha2": "CM",
		"alpha3": "CMR",
		"numeric": "120",
		"fips": "CM",
		"Country": "Cameroon",
		"Capital": "Yaounde",
		"Area in km²": "475440",
		"Population": "19294149",
		"Continent": "AF"
	},
	{
		"alpha2": "CN",
		"alpha3": "CHN",
		"numeric": "156",
		"fips": "CH",
		"Country": "China",
		"Capital": "Beijing",
		"Area in km²": "9596960",
		"Population": "1330044000",
		"Continent": "AS"
	},
	{
		"alpha2": "CO",
		"alpha3": "COL",
		"numeric": "170",
		"fips": "CO",
		"Country": "Colombia",
		"Capital": "Bogota",
		"Area in km²": "1138910",
		"Population": "44205293",
		"Continent": "SA"
	},
	{
		"alpha2": "CR",
		"alpha3": "CRI",
		"numeric": "188",
		"fips": "CS",
		"Country": "Costa Rica",
		"Capital": "San Jose",
		"Area in km²": "51100",
		"Population": "4516220",
		"Continent": "NA"
	},
	{
		"alpha2": "CS",
		"alpha3": "SCG",
		"numeric": "891",
		"fips": "YI",
		"Country": "",
		"Capital": "Belgrade",
		"Area in km²": "102350",
		"Population": "10829175",
		"Continent": "EU"
	},
	{
		"alpha2": "CU",
		"alpha3": "CUB",
		"numeric": "192",
		"fips": "CU",
		"Country": "Cuba",
		"Capital": "Havana",
		"Area in km²": "110860",
		"Population": "11423000",
		"Continent": "NA"
	},
	{
		"alpha2": "CV",
		"alpha3": "CPV",
		"numeric": "132",
		"fips": "CV",
		"Country": "Cape Verde",
		"Capital": "Praia",
		"Area in km²": "4033",
		"Population": "508659",
		"Continent": "AF"
	},
	{
		"alpha2": "CW",
		"alpha3": "CUW",
		"numeric": "531",
		"fips": "UC",
		"Country": "Curacao",
		"Capital": "Willemstad",
		"Area in km²": "",
		"Population": "141766",
		"Continent": "NA"
	},
	{
		"alpha2": "CX",
		"alpha3": "CXR",
		"numeric": "162",
		"fips": "KT",
		"Country": "Christmas Island",
		"Capital": "Flying Fish Cove",
		"Area in km²": "135",
		"Population": "1500",
		"Continent": "AS"
	},
	{
		"alpha2": "CY",
		"alpha3": "CYP",
		"numeric": "196",
		"fips": "CY",
		"Country": "Cyprus",
		"Capital": "Nicosia",
		"Area in km²": "9250",
		"Population": "1102677",
		"Continent": "EU"
	},
	{
		"alpha2": "CZ",
		"alpha3": "CZE",
		"numeric": "203",
		"fips": "EZ",
		"Country": "Czechia",
		"Capital": "Prague",
		"Area in km²": "78866",
		"Population": "10476000",
		"Continent": "EU"
	},
	{
		"alpha2": "DE",
		"alpha3": "DEU",
		"numeric": "276",
		"fips": "GM",
		"Country": "Germany",
		"Capital": "Berlin",
		"Area in km²": "357021",
		"Population": "81802257",
		"Continent": "EU"
	},
	{
		"alpha2": "DJ",
		"alpha3": "DJI",
		"numeric": "262",
		"fips": "DJ",
		"Country": "Djibouti",
		"Capital": "Djibouti",
		"Area in km²": "23000",
		"Population": "740528",
		"Continent": "AF"
	},
	{
		"alpha2": "DK",
		"alpha3": "DNK",
		"numeric": "208",
		"fips": "DA",
		"Country": "Denmark",
		"Capital": "Copenhagen",
		"Area in km²": "43094",
		"Population": "5484000",
		"Continent": "EU"
	},
	{
		"alpha2": "DM",
		"alpha3": "DMA",
		"numeric": "212",
		"fips": "DO",
		"Country": "Dominica",
		"Capital": "Roseau",
		"Area in km²": "754",
		"Population": "72813",
		"Continent": "NA"
	},
	{
		"alpha2": "DO",
		"alpha3": "DOM",
		"numeric": "214",
		"fips": "DR",
		"Country": "Dominican Republic",
		"Capital": "Santo Domingo",
		"Area in km²": "48730",
		"Population": "9823821",
		"Continent": "NA"
	},
	{
		"alpha2": "DZ",
		"alpha3": "DZA",
		"numeric": "12",
		"fips": "AG",
		"Country": "Algeria",
		"Capital": "Algiers",
		"Area in km²": "2381740",
		"Population": "34586184",
		"Continent": "AF"
	},
	{
		"alpha2": "EC",
		"alpha3": "ECU",
		"numeric": "218",
		"fips": "EC",
		"Country": "Ecuador",
		"Capital": "Quito",
		"Area in km²": "283560",
		"Population": "14790608",
		"Continent": "SA"
	},
	{
		"alpha2": "EE",
		"alpha3": "EST",
		"numeric": "233",
		"fips": "EN",
		"Country": "Estonia",
		"Capital": "Tallinn",
		"Area in km²": "45226",
		"Population": "1291170",
		"Continent": "EU"
	},
	{
		"alpha2": "EG",
		"alpha3": "EGY",
		"numeric": "818",
		"fips": "EG",
		"Country": "Egypt",
		"Capital": "Cairo",
		"Area in km²": "1001450",
		"Population": "80471869",
		"Continent": "AF"
	},
	{
		"alpha2": "EH",
		"alpha3": "ESH",
		"numeric": "732",
		"fips": "WI",
		"Country": "Western Sahara",
		"Capital": "El-Aaiun",
		"Area in km²": "266000",
		"Population": "273008",
		"Continent": "AF"
	},
	{
		"alpha2": "ER",
		"alpha3": "ERI",
		"numeric": "232",
		"fips": "ER",
		"Country": "Eritrea",
		"Capital": "Asmara",
		"Area in km²": "121320",
		"Population": "5792984",
		"Continent": "AF"
	},
	{
		"alpha2": "ES",
		"alpha3": "ESP",
		"numeric": "724",
		"fips": "SP",
		"Country": "Spain",
		"Capital": "Madrid",
		"Area in km²": "504782",
		"Population": "46505963",
		"Continent": "EU"
	},
	{
		"alpha2": "ET",
		"alpha3": "ETH",
		"numeric": "231",
		"fips": "ET",
		"Country": "Ethiopia",
		"Capital": "Addis Ababa",
		"Area in km²": "1127127",
		"Population": "88013491",
		"Continent": "AF"
	},
	{
		"alpha2": "FI",
		"alpha3": "FIN",
		"numeric": "246",
		"fips": "FI",
		"Country": "Finland",
		"Capital": "Helsinki",
		"Area in km²": "337030",
		"Population": "5244000",
		"Continent": "EU"
	},
	{
		"alpha2": "FJ",
		"alpha3": "FJI",
		"numeric": "242",
		"fips": "FJ",
		"Country": "Fiji",
		"Capital": "Suva",
		"Area in km²": "18270",
		"Population": "875983",
		"Continent": "OC"
	},
	{
		"alpha2": "FK",
		"alpha3": "FLK",
		"numeric": "238",
		"fips": "FK",
		"Country": "Falkland Islands",
		"Capital": "Stanley",
		"Area in km²": "12173",
		"Population": "2638",
		"Continent": "SA"
	},
	{
		"alpha2": "FM",
		"alpha3": "FSM",
		"numeric": "583",
		"fips": "FM",
		"Country": "Micronesia",
		"Capital": "Palikir",
		"Area in km²": "702",
		"Population": "107708",
		"Continent": "OC"
	},
	{
		"alpha2": "FO",
		"alpha3": "FRO",
		"numeric": "234",
		"fips": "FO",
		"Country": "Faroe Islands",
		"Capital": "Torshavn",
		"Area in km²": "1399",
		"Population": "48228",
		"Continent": "EU"
	},
	{
		"alpha2": "FR",
		"alpha3": "FRA",
		"numeric": "250",
		"fips": "FR",
		"Country": "France",
		"Capital": "Paris",
		"Area in km²": "547030",
		"Population": "64768389",
		"Continent": "EU"
	},
	{
		"alpha2": "GA",
		"alpha3": "GAB",
		"numeric": "266",
		"fips": "GB",
		"Country": "Gabon",
		"Capital": "Libreville",
		"Area in km²": "267667",
		"Population": "1545255",
		"Continent": "AF"
	},
	{
		"alpha2": "GB",
		"alpha3": "GBR",
		"numeric": "826",
		"fips": "UK",
		"Country": "United Kingdom",
		"Capital": "London",
		"Area in km²": "244820",
		"Population": "62348447",
		"Continent": "EU"
	},
	{
		"alpha2": "GD",
		"alpha3": "GRD",
		"numeric": "308",
		"fips": "GJ",
		"Country": "Grenada",
		"Capital": "St. George's",
		"Area in km²": "344",
		"Population": "107818",
		"Continent": "NA"
	},
	{
		"alpha2": "GE",
		"alpha3": "GEO",
		"numeric": "268",
		"fips": "GG",
		"Country": "Georgia",
		"Capital": "Tbilisi",
		"Area in km²": "69700",
		"Population": "4630000",
		"Continent": "AS"
	},
	{
		"alpha2": "GF",
		"alpha3": "GUF",
		"numeric": "254",
		"fips": "FG",
		"Country": "French Guiana",
		"Capital": "Cayenne",
		"Area in km²": "91000",
		"Population": "195506",
		"Continent": "SA"
	},
	{
		"alpha2": "GG",
		"alpha3": "GGY",
		"numeric": "831",
		"fips": "GK",
		"Country": "Guernsey",
		"Capital": "St Peter Port",
		"Area in km²": "78",
		"Population": "65228",
		"Continent": "EU"
	},
	{
		"alpha2": "GH",
		"alpha3": "GHA",
		"numeric": "288",
		"fips": "GH",
		"Country": "Ghana",
		"Capital": "Accra",
		"Area in km²": "239460",
		"Population": "24339838",
		"Continent": "AF"
	},
	{
		"alpha2": "GI",
		"alpha3": "GIB",
		"numeric": "292",
		"fips": "GI",
		"Country": "Gibraltar",
		"Capital": "Gibraltar",
		"Area in km²": "6.5",
		"Population": "27884",
		"Continent": "EU"
	},
	{
		"alpha2": "GL",
		"alpha3": "GRL",
		"numeric": "304",
		"fips": "GL",
		"Country": "Greenland",
		"Capital": "Nuuk",
		"Area in km²": "2166086",
		"Population": "56375",
		"Continent": "NA"
	},
	{
		"alpha2": "GM",
		"alpha3": "GMB",
		"numeric": "270",
		"fips": "GA",
		"Country": "Gambia",
		"Capital": "Banjul",
		"Area in km²": "11300",
		"Population": "1593256",
		"Continent": "AF"
	},
	{
		"alpha2": "GN",
		"alpha3": "GIN",
		"numeric": "324",
		"fips": "GV",
		"Country": "Guinea",
		"Capital": "Conakry",
		"Area in km²": "245857",
		"Population": "10324025",
		"Continent": "AF"
	},
	{
		"alpha2": "GP",
		"alpha3": "GLP",
		"numeric": "312",
		"fips": "GP",
		"Country": "Guadeloupe",
		"Capital": "Basse-Terre",
		"Area in km²": "1780",
		"Population": "443000",
		"Continent": "NA"
	},
	{
		"alpha2": "GQ",
		"alpha3": "GNQ",
		"numeric": "226",
		"fips": "EK",
		"Country": "Equatorial Guinea",
		"Capital": "Malabo",
		"Area in km²": "28051",
		"Population": "1014999",
		"Continent": "AF"
	},
	{
		"alpha2": "GR",
		"alpha3": "GRC",
		"numeric": "300",
		"fips": "GR",
		"Country": "Greece",
		"Capital": "Athens",
		"Area in km²": "131940",
		"Population": "11000000",
		"Continent": "EU"
	},
	{
		"alpha2": "GS",
		"alpha3": "SGS",
		"numeric": "239",
		"fips": "SX",
		"Country": "South Georgia and the South Sandwich Islands",
		"Capital": "Grytviken",
		"Area in km²": "3903",
		"Population": "30",
		"Continent": "AN"
	},
	{
		"alpha2": "GT",
		"alpha3": "GTM",
		"numeric": "320",
		"fips": "GT",
		"Country": "Guatemala",
		"Capital": "Guatemala City",
		"Area in km²": "108890",
		"Population": "13550440",
		"Continent": "NA"
	},
	{
		"alpha2": "GU",
		"alpha3": "GUM",
		"numeric": "316",
		"fips": "GQ",
		"Country": "Guam",
		"Capital": "Hagatna",
		"Area in km²": "549",
		"Population": "159358",
		"Continent": "OC"
	},
	{
		"alpha2": "GW",
		"alpha3": "GNB",
		"numeric": "624",
		"fips": "PU",
		"Country": "Guinea-Bissau",
		"Capital": "Bissau",
		"Area in km²": "36120",
		"Population": "1565126",
		"Continent": "AF"
	},
	{
		"alpha2": "GY",
		"alpha3": "GUY",
		"numeric": "328",
		"fips": "GY",
		"Country": "Guyana",
		"Capital": "Georgetown",
		"Area in km²": "214970",
		"Population": "748486",
		"Continent": "SA"
	},
	{
		"alpha2": "HK",
		"alpha3": "HKG",
		"numeric": "344",
		"fips": "HK",
		"Country": "Hong Kong",
		"Capital": "Hong Kong",
		"Area in km²": "1092",
		"Population": "6898686",
		"Continent": "AS"
	},
	{
		"alpha2": "HM",
		"alpha3": "HMD",
		"numeric": "334",
		"fips": "HM",
		"Country": "Heard Island and McDonald Islands",
		"Capital": "",
		"Area in km²": "412",
		"Population": "0",
		"Continent": "AN"
	},
	{
		"alpha2": "HN",
		"alpha3": "HND",
		"numeric": "340",
		"fips": "HO",
		"Country": "Honduras",
		"Capital": "Tegucigalpa",
		"Area in km²": "112090",
		"Population": "7989415",
		"Continent": "NA"
	},
	{
		"alpha2": "HR",
		"alpha3": "HRV",
		"numeric": "191",
		"fips": "HR",
		"Country": "Croatia",
		"Capital": "Zagreb",
		"Area in km²": "56542",
		"Population": "4491000",
		"Continent": "EU"
	},
	{
		"alpha2": "HT",
		"alpha3": "HTI",
		"numeric": "332",
		"fips": "HA",
		"Country": "Haiti",
		"Capital": "Port-au-Prince",
		"Area in km²": "27750",
		"Population": "9648924",
		"Continent": "NA"
	},
	{
		"alpha2": "HU",
		"alpha3": "HUN",
		"numeric": "348",
		"fips": "HU",
		"Country": "Hungary",
		"Capital": "Budapest",
		"Area in km²": "93030",
		"Population": "9982000",
		"Continent": "EU"
	},
	{
		"alpha2": "ID",
		"alpha3": "IDN",
		"numeric": "360",
		"fips": "ID",
		"Country": "Indonesia",
		"Capital": "Jakarta",
		"Area in km²": "1919440",
		"Population": "242968342",
		"Continent": "AS"
	},
	{
		"alpha2": "IE",
		"alpha3": "IRL",
		"numeric": "372",
		"fips": "EI",
		"Country": "Ireland",
		"Capital": "Dublin",
		"Area in km²": "70280",
		"Population": "4622917",
		"Continent": "EU"
	},
	{
		"alpha2": "IL",
		"alpha3": "ISR",
		"numeric": "376",
		"fips": "IS",
		"Country": "Israel",
		"Capital": "Jerusalem",
		"Area in km²": "20770",
		"Population": "7353985",
		"Continent": "AS"
	},
	{
		"alpha2": "IM",
		"alpha3": "IMN",
		"numeric": "833",
		"fips": "IM",
		"Country": "Isle of Man",
		"Capital": "Douglas, Isle of Man",
		"Area in km²": "572",
		"Population": "75049",
		"Continent": "EU"
	},
	{
		"alpha2": "IN",
		"alpha3": "IND",
		"numeric": "356",
		"fips": "IN",
		"Country": "India",
		"Capital": "New Delhi",
		"Area in km²": "3287590",
		"Population": "1173108018",
		"Continent": "AS"
	},
	{
		"alpha2": "IO",
		"alpha3": "IOT",
		"numeric": "86",
		"fips": "IO",
		"Country": "British Indian Ocean Territory",
		"Capital": "Diego Garcia",
		"Area in km²": "60",
		"Population": "4000",
		"Continent": "AS"
	},
	{
		"alpha2": "IQ",
		"alpha3": "IRQ",
		"numeric": "368",
		"fips": "IZ",
		"Country": "Iraq",
		"Capital": "Baghdad",
		"Area in km²": "437072",
		"Population": "29671605",
		"Continent": "AS"
	},
	{
		"alpha2": "IR",
		"alpha3": "IRN",
		"numeric": "364",
		"fips": "IR",
		"Country": "Iran",
		"Capital": "Tehran",
		"Area in km²": "1648000",
		"Population": "76923300",
		"Continent": "AS"
	},
	{
		"alpha2": "IS",
		"alpha3": "ISL",
		"numeric": "352",
		"fips": "IC",
		"Country": "Iceland",
		"Capital": "Reykjavik",
		"Area in km²": "103000",
		"Population": "308910",
		"Continent": "EU"
	},
	{
		"alpha2": "IT",
		"alpha3": "ITA",
		"numeric": "380",
		"fips": "IT",
		"Country": "Italy",
		"Capital": "Rome",
		"Area in km²": "301230",
		"Population": "60340328",
		"Continent": "EU"
	},
	{
		"alpha2": "JE",
		"alpha3": "JEY",
		"numeric": "832",
		"fips": "JE",
		"Country": "Jersey",
		"Capital": "Saint Helier",
		"Area in km²": "116",
		"Population": "90812",
		"Continent": "EU"
	},
	{
		"alpha2": "JM",
		"alpha3": "JAM",
		"numeric": "388",
		"fips": "JM",
		"Country": "Jamaica",
		"Capital": "Kingston",
		"Area in km²": "10991",
		"Population": "2847232",
		"Continent": "NA"
	},
	{
		"alpha2": "JO",
		"alpha3": "JOR",
		"numeric": "400",
		"fips": "JO",
		"Country": "Jordan",
		"Capital": "Amman",
		"Area in km²": "92300",
		"Population": "6407085",
		"Continent": "AS"
	},
	{
		"alpha2": "JP",
		"alpha3": "JPN",
		"numeric": "392",
		"fips": "JA",
		"Country": "Japan",
		"Capital": "Tokyo",
		"Area in km²": "377835",
		"Population": "127288000",
		"Continent": "AS"
	},
	{
		"alpha2": "KE",
		"alpha3": "KEN",
		"numeric": "404",
		"fips": "KE",
		"Country": "Kenya",
		"Capital": "Nairobi",
		"Area in km²": "582650",
		"Population": "40046566",
		"Continent": "AF"
	},
	{
		"alpha2": "KG",
		"alpha3": "KGZ",
		"numeric": "417",
		"fips": "KG",
		"Country": "Kyrgyzstan",
		"Capital": "Bishkek",
		"Area in km²": "198500",
		"Population": "5508626",
		"Continent": "AS"
	},
	{
		"alpha2": "KH",
		"alpha3": "KHM",
		"numeric": "116",
		"fips": "CB",
		"Country": "Cambodia",
		"Capital": "Phnom Penh",
		"Area in km²": "181040",
		"Population": "14453680",
		"Continent": "AS"
	},
	{
		"alpha2": "KI",
		"alpha3": "KIR",
		"numeric": "296",
		"fips": "KR",
		"Country": "Kiribati",
		"Capital": "Tarawa",
		"Area in km²": "811",
		"Population": "92533",
		"Continent": "OC"
	},
	{
		"alpha2": "KM",
		"alpha3": "COM",
		"numeric": "174",
		"fips": "CN",
		"Country": "Comoros",
		"Capital": "Moroni",
		"Area in km²": "2170",
		"Population": "773407",
		"Continent": "AF"
	},
	{
		"alpha2": "KN",
		"alpha3": "KNA",
		"numeric": "659",
		"fips": "SC",
		"Country": "Saint Kitts and Nevis",
		"Capital": "Basseterre",
		"Area in km²": "261",
		"Population": "49898",
		"Continent": "NA"
	},
	{
		"alpha2": "KP",
		"alpha3": "PRK",
		"numeric": "408",
		"fips": "KN",
		"Country": "North Korea",
		"Capital": "Pyongyang",
		"Area in km²": "120540",
		"Population": "22912177",
		"Continent": "AS"
	},
	{
		"alpha2": "KR",
		"alpha3": "KOR",
		"numeric": "410",
		"fips": "KS",
		"Country": "South Korea",
		"Capital": "Seoul",
		"Area in km²": "98480",
		"Population": "48422644",
		"Continent": "AS"
	},
	{
		"alpha2": "KW",
		"alpha3": "KWT",
		"numeric": "414",
		"fips": "KU",
		"Country": "Kuwait",
		"Capital": "Kuwait City",
		"Area in km²": "17820",
		"Population": "2789132",
		"Continent": "AS"
	},
	{
		"alpha2": "KY",
		"alpha3": "CYM",
		"numeric": "136",
		"fips": "CJ",
		"Country": "Cayman Islands",
		"Capital": "George Town",
		"Area in km²": "262",
		"Population": "44270",
		"Continent": "NA"
	},
	{
		"alpha2": "KZ",
		"alpha3": "KAZ",
		"numeric": "398",
		"fips": "KZ",
		"Country": "Kazakhstan",
		"Capital": "Astana",
		"Area in km²": "2717300",
		"Population": "15340000",
		"Continent": "AS"
	},
	{
		"alpha2": "LA",
		"alpha3": "LAO",
		"numeric": "418",
		"fips": "LA",
		"Country": "Laos",
		"Capital": "Vientiane",
		"Area in km²": "236800",
		"Population": "6368162",
		"Continent": "AS"
	},
	{
		"alpha2": "LB",
		"alpha3": "LBN",
		"numeric": "422",
		"fips": "LE",
		"Country": "Lebanon",
		"Capital": "Beirut",
		"Area in km²": "10400",
		"Population": "4125247",
		"Continent": "AS"
	},
	{
		"alpha2": "LC",
		"alpha3": "LCA",
		"numeric": "662",
		"fips": "ST",
		"Country": "Saint Lucia",
		"Capital": "Castries",
		"Area in km²": "616",
		"Population": "160922",
		"Continent": "NA"
	},
	{
		"alpha2": "LI",
		"alpha3": "LIE",
		"numeric": "438",
		"fips": "LS",
		"Country": "Liechtenstein",
		"Capital": "Vaduz",
		"Area in km²": "160",
		"Population": "35000",
		"Continent": "EU"
	},
	{
		"alpha2": "LK",
		"alpha3": "LKA",
		"numeric": "144",
		"fips": "CE",
		"Country": "Sri Lanka",
		"Capital": "Colombo",
		"Area in km²": "65610",
		"Population": "21513990",
		"Continent": "AS"
	},
	{
		"alpha2": "LR",
		"alpha3": "LBR",
		"numeric": "430",
		"fips": "LI",
		"Country": "Liberia",
		"Capital": "Monrovia",
		"Area in km²": "111370",
		"Population": "3685076",
		"Continent": "AF"
	},
	{
		"alpha2": "LS",
		"alpha3": "LSO",
		"numeric": "426",
		"fips": "LT",
		"Country": "Lesotho",
		"Capital": "Maseru",
		"Area in km²": "30355",
		"Population": "1919552",
		"Continent": "AF"
	},
	{
		"alpha2": "LT",
		"alpha3": "LTU",
		"numeric": "440",
		"fips": "LH",
		"Country": "Lithuania",
		"Capital": "Vilnius",
		"Area in km²": "65200",
		"Population": "3565000",
		"Continent": "EU"
	},
	{
		"alpha2": "LU",
		"alpha3": "LUX",
		"numeric": "442",
		"fips": "LU",
		"Country": "Luxembourg",
		"Capital": "Luxembourg",
		"Area in km²": "2586",
		"Population": "497538",
		"Continent": "EU"
	},
	{
		"alpha2": "LV",
		"alpha3": "LVA",
		"numeric": "428",
		"fips": "LG",
		"Country": "Latvia",
		"Capital": "Riga",
		"Area in km²": "64589",
		"Population": "2217969",
		"Continent": "EU"
	},
	{
		"alpha2": "LY",
		"alpha3": "LBY",
		"numeric": "434",
		"fips": "LY",
		"Country": "Libya",
		"Capital": "Tripolis",
		"Area in km²": "1759540",
		"Population": "6461454",
		"Continent": "AF"
	},
	{
		"alpha2": "MA",
		"alpha3": "MAR",
		"numeric": "504",
		"fips": "MO",
		"Country": "Morocco",
		"Capital": "Rabat",
		"Area in km²": "446550",
		"Population": "31627428",
		"Continent": "AF"
	},
	{
		"alpha2": "MC",
		"alpha3": "MCO",
		"numeric": "492",
		"fips": "MN",
		"Country": "Monaco",
		"Capital": "Monaco",
		"Area in km²": "2",
		"Population": "32965",
		"Continent": "EU"
	},
	{
		"alpha2": "MD",
		"alpha3": "MDA",
		"numeric": "498",
		"fips": "MD",
		"Country": "Moldova",
		"Capital": "Chisinau",
		"Area in km²": "33843",
		"Population": "4324000",
		"Continent": "EU"
	},
	{
		"alpha2": "ME",
		"alpha3": "MNE",
		"numeric": "499",
		"fips": "MJ",
		"Country": "Montenegro",
		"Capital": "Podgorica",
		"Area in km²": "14026",
		"Population": "666730",
		"Continent": "EU"
	},
	{
		"alpha2": "MF",
		"alpha3": "MAF",
		"numeric": "663",
		"fips": "RN",
		"Country": "Saint Martin",
		"Capital": "Marigot",
		"Area in km²": "53",
		"Population": "35925",
		"Continent": "NA"
	},
	{
		"alpha2": "MG",
		"alpha3": "MDG",
		"numeric": "450",
		"fips": "MA",
		"Country": "Madagascar",
		"Capital": "Antananarivo",
		"Area in km²": "587040",
		"Population": "21281844",
		"Continent": "AF"
	},
	{
		"alpha2": "MH",
		"alpha3": "MHL",
		"numeric": "584",
		"fips": "RM",
		"Country": "Marshall Islands",
		"Capital": "Majuro",
		"Area in km²": "181.3",
		"Population": "65859",
		"Continent": "OC"
	},
	{
		"alpha2": "MK",
		"alpha3": "MKD",
		"numeric": "807",
		"fips": "MK",
		"Country": "Macedonia",
		"Capital": "Skopje",
		"Area in km²": "25333",
		"Population": "2061000",
		"Continent": "EU"
	},
	{
		"alpha2": "ML",
		"alpha3": "MLI",
		"numeric": "466",
		"fips": "ML",
		"Country": "Mali",
		"Capital": "Bamako",
		"Area in km²": "1240000",
		"Population": "13796354",
		"Continent": "AF"
	},
	{
		"alpha2": "MM",
		"alpha3": "MMR",
		"numeric": "104",
		"fips": "BM",
		"Country": "Myanmar [Burma]",
		"Capital": "Nay Pyi Taw",
		"Area in km²": "678500",
		"Population": "53414374",
		"Continent": "AS"
	},
	{
		"alpha2": "MN",
		"alpha3": "MNG",
		"numeric": "496",
		"fips": "MG",
		"Country": "Mongolia",
		"Capital": "Ulan Bator",
		"Area in km²": "1565000",
		"Population": "3086918",
		"Continent": "AS"
	},
	{
		"alpha2": "MO",
		"alpha3": "MAC",
		"numeric": "446",
		"fips": "MC",
		"Country": "Macao",
		"Capital": "Macao",
		"Area in km²": "254",
		"Population": "449198",
		"Continent": "AS"
	},
	{
		"alpha2": "MP",
		"alpha3": "MNP",
		"numeric": "580",
		"fips": "CQ",
		"Country": "Northern Mariana Islands",
		"Capital": "Saipan",
		"Area in km²": "477",
		"Population": "53883",
		"Continent": "OC"
	},
	{
		"alpha2": "MQ",
		"alpha3": "MTQ",
		"numeric": "474",
		"fips": "MB",
		"Country": "Martinique",
		"Capital": "Fort-de-France",
		"Area in km²": "1100",
		"Population": "432900",
		"Continent": "NA"
	},
	{
		"alpha2": "MR",
		"alpha3": "MRT",
		"numeric": "478",
		"fips": "MR",
		"Country": "Mauritania",
		"Capital": "Nouakchott",
		"Area in km²": "1030700",
		"Population": "3205060",
		"Continent": "AF"
	},
	{
		"alpha2": "MS",
		"alpha3": "MSR",
		"numeric": "500",
		"fips": "MH",
		"Country": "Montserrat",
		"Capital": "Plymouth",
		"Area in km²": "102",
		"Population": "9341",
		"Continent": "NA"
	},
	{
		"alpha2": "MT",
		"alpha3": "MLT",
		"numeric": "470",
		"fips": "MT",
		"Country": "Malta",
		"Capital": "Valletta",
		"Area in km²": "316",
		"Population": "403000",
		"Continent": "EU"
	},
	{
		"alpha2": "MU",
		"alpha3": "MUS",
		"numeric": "480",
		"fips": "MP",
		"Country": "Mauritius",
		"Capital": "Port Louis",
		"Area in km²": "2040",
		"Population": "1294104",
		"Continent": "AF"
	},
	{
		"alpha2": "MV",
		"alpha3": "MDV",
		"numeric": "462",
		"fips": "MV",
		"Country": "Maldives",
		"Capital": "Male",
		"Area in km²": "300",
		"Population": "395650",
		"Continent": "AS"
	},
	{
		"alpha2": "MW",
		"alpha3": "MWI",
		"numeric": "454",
		"fips": "MI",
		"Country": "Malawi",
		"Capital": "Lilongwe",
		"Area in km²": "118480",
		"Population": "15447500",
		"Continent": "AF"
	},
	{
		"alpha2": "MX",
		"alpha3": "MEX",
		"numeric": "484",
		"fips": "MX",
		"Country": "Mexico",
		"Capital": "Mexico City",
		"Area in km²": "1972550",
		"Population": "112468855",
		"Continent": "NA"
	},
	{
		"alpha2": "MY",
		"alpha3": "MYS",
		"numeric": "458",
		"fips": "MY",
		"Country": "Malaysia",
		"Capital": "Kuala Lumpur",
		"Area in km²": "329750",
		"Population": "28274729",
		"Continent": "AS"
	},
	{
		"alpha2": "MZ",
		"alpha3": "MOZ",
		"numeric": "508",
		"fips": "MZ",
		"Country": "Mozambique",
		"Capital": "Maputo",
		"Area in km²": "801590",
		"Population": "22061451",
		"Continent": "AF"
	},
	{
		"alpha2": "NA",
		"alpha3": "NAM",
		"numeric": "516",
		"fips": "WA",
		"Country": "Namibia",
		"Capital": "Windhoek",
		"Area in km²": "825418",
		"Population": "2128471",
		"Continent": "AF"
	},
	{
		"alpha2": "NC",
		"alpha3": "NCL",
		"numeric": "540",
		"fips": "NC",
		"Country": "New Caledonia",
		"Capital": "Noumea",
		"Area in km²": "19060",
		"Population": "216494",
		"Continent": "OC"
	},
	{
		"alpha2": "NE",
		"alpha3": "NER",
		"numeric": "562",
		"fips": "NG",
		"Country": "Niger",
		"Capital": "Niamey",
		"Area in km²": "1267000",
		"Population": "15878271",
		"Continent": "AF"
	},
	{
		"alpha2": "NF",
		"alpha3": "NFK",
		"numeric": "574",
		"fips": "NF",
		"Country": "Norfolk Island",
		"Capital": "Kingston",
		"Area in km²": "34.6",
		"Population": "1828",
		"Continent": "OC"
	},
	{
		"alpha2": "NG",
		"alpha3": "NGA",
		"numeric": "566",
		"fips": "NI",
		"Country": "Nigeria",
		"Capital": "Abuja",
		"Area in km²": "923768",
		"Population": "154000000",
		"Continent": "AF"
	},
	{
		"alpha2": "NI",
		"alpha3": "NIC",
		"numeric": "558",
		"fips": "NU",
		"Country": "Nicaragua",
		"Capital": "Managua",
		"Area in km²": "129494",
		"Population": "5995928",
		"Continent": "NA"
	},
	{
		"alpha2": "NL",
		"alpha3": "NLD",
		"numeric": "528",
		"fips": "NL",
		"Country": "Netherlands",
		"Capital": "Amsterdam",
		"Area in km²": "41526",
		"Population": "16645000",
		"Continent": "EU"
	},
	{
		"alpha2": "NO",
		"alpha3": "NOR",
		"numeric": "578",
		"fips": "NO",
		"Country": "Norway",
		"Capital": "Oslo",
		"Area in km²": "324220",
		"Population": "5009150",
		"Continent": "EU"
	},
	{
		"alpha2": "NP",
		"alpha3": "NPL",
		"numeric": "524",
		"fips": "NP",
		"Country": "Nepal",
		"Capital": "Kathmandu",
		"Area in km²": "140800",
		"Population": "28951852",
		"Continent": "AS"
	},
	{
		"alpha2": "NR",
		"alpha3": "NRU",
		"numeric": "520",
		"fips": "NR",
		"Country": "Nauru",
		"Capital": "Yaren",
		"Area in km²": "21",
		"Population": "10065",
		"Continent": "OC"
	},
	{
		"alpha2": "NU",
		"alpha3": "NIU",
		"numeric": "570",
		"fips": "NE",
		"Country": "Niue",
		"Capital": "Alofi",
		"Area in km²": "260",
		"Population": "2166",
		"Continent": "OC"
	},
	{
		"alpha2": "NZ",
		"alpha3": "NZL",
		"numeric": "554",
		"fips": "NZ",
		"Country": "New Zealand",
		"Capital": "Wellington",
		"Area in km²": "268680",
		"Population": "4252277",
		"Continent": "OC"
	},
	{
		"alpha2": "OM",
		"alpha3": "OMN",
		"numeric": "512",
		"fips": "MU",
		"Country": "Oman",
		"Capital": "Muscat",
		"Area in km²": "212460",
		"Population": "2967717",
		"Continent": "AS"
	},
	{
		"alpha2": "PA",
		"alpha3": "PAN",
		"numeric": "591",
		"fips": "PM",
		"Country": "Panama",
		"Capital": "Panama City",
		"Area in km²": "78200",
		"Population": "3410676",
		"Continent": "NA"
	},
	{
		"alpha2": "PE",
		"alpha3": "PER",
		"numeric": "604",
		"fips": "PE",
		"Country": "Peru",
		"Capital": "Lima",
		"Area in km²": "1285220",
		"Population": "29907003",
		"Continent": "SA"
	},
	{
		"alpha2": "PF",
		"alpha3": "PYF",
		"numeric": "258",
		"fips": "FP",
		"Country": "French Polynesia",
		"Capital": "Papeete",
		"Area in km²": "4167",
		"Population": "270485",
		"Continent": "OC"
	},
	{
		"alpha2": "PG",
		"alpha3": "PNG",
		"numeric": "598",
		"fips": "PP",
		"Country": "Papua New Guinea",
		"Capital": "Port Moresby",
		"Area in km²": "462840",
		"Population": "6064515",
		"Continent": "OC"
	},
	{
		"alpha2": "PH",
		"alpha3": "PHL",
		"numeric": "608",
		"fips": "RP",
		"Country": "Philippines",
		"Capital": "Manila",
		"Area in km²": "300000",
		"Population": "99900177",
		"Continent": "AS"
	},
	{
		"alpha2": "PK",
		"alpha3": "PAK",
		"numeric": "586",
		"fips": "PK",
		"Country": "Pakistan",
		"Capital": "Islamabad",
		"Area in km²": "803940",
		"Population": "184404791",
		"Continent": "AS"
	},
	{
		"alpha2": "PL",
		"alpha3": "POL",
		"numeric": "616",
		"fips": "PL",
		"Country": "Poland",
		"Capital": "Warsaw",
		"Area in km²": "312685",
		"Population": "38500000",
		"Continent": "EU"
	},
	{
		"alpha2": "PM",
		"alpha3": "SPM",
		"numeric": "666",
		"fips": "SB",
		"Country": "Saint Pierre and Miquelon",
		"Capital": "Saint-Pierre",
		"Area in km²": "242",
		"Population": "7012",
		"Continent": "NA"
	},
	{
		"alpha2": "PN",
		"alpha3": "PCN",
		"numeric": "612",
		"fips": "PC",
		"Country": "Pitcairn Islands",
		"Capital": "Adamstown",
		"Area in km²": "47",
		"Population": "46",
		"Continent": "OC"
	},
	{
		"alpha2": "PR",
		"alpha3": "PRI",
		"numeric": "630",
		"fips": "RQ",
		"Country": "Puerto Rico",
		"Capital": "San Juan",
		"Area in km²": "9104",
		"Population": "3916632",
		"Continent": "NA"
	},
	{
		"alpha2": "PS",
		"alpha3": "PSE",
		"numeric": "275",
		"fips": "WE",
		"Country": "Palestine",
		"Capital": "East Jerusalem",
		"Area in km²": "5970",
		"Population": "3800000",
		"Continent": "AS"
	},
	{
		"alpha2": "PT",
		"alpha3": "PRT",
		"numeric": "620",
		"fips": "PO",
		"Country": "Portugal",
		"Capital": "Lisbon",
		"Area in km²": "92391",
		"Population": "10676000",
		"Continent": "EU"
	},
	{
		"alpha2": "PW",
		"alpha3": "PLW",
		"numeric": "585",
		"fips": "PS",
		"Country": "Palau",
		"Capital": "Melekeok",
		"Area in km²": "458",
		"Population": "19907",
		"Continent": "OC"
	},
	{
		"alpha2": "PY",
		"alpha3": "PRY",
		"numeric": "600",
		"fips": "PA",
		"Country": "Paraguay",
		"Capital": "Asuncion",
		"Area in km²": "406750",
		"Population": "6375830",
		"Continent": "SA"
	},
	{
		"alpha2": "QA",
		"alpha3": "QAT",
		"numeric": "634",
		"fips": "QA",
		"Country": "Qatar",
		"Capital": "Doha",
		"Area in km²": "11437",
		"Population": "840926",
		"Continent": "AS"
	},
	{
		"alpha2": "RE",
		"alpha3": "REU",
		"numeric": "638",
		"fips": "RE",
		"Country": "Réunion",
		"Capital": "Saint-Denis",
		"Area in km²": "2517",
		"Population": "776948",
		"Continent": "AF"
	},
	{
		"alpha2": "RO",
		"alpha3": "ROU",
		"numeric": "642",
		"fips": "RO",
		"Country": "Romania",
		"Capital": "Bucharest",
		"Area in km²": "237500",
		"Population": "21959278",
		"Continent": "EU"
	},
	{
		"alpha2": "RS",
		"alpha3": "SRB",
		"numeric": "688",
		"fips": "RI",
		"Country": "Serbia",
		"Capital": "Belgrade",
		"Area in km²": "88361",
		"Population": "7344847",
		"Continent": "EU"
	},
	{
		"alpha2": "RU",
		"alpha3": "RUS",
		"numeric": "643",
		"fips": "RS",
		"Country": "Russia",
		"Capital": "Moscow",
		"Area in km²": "17100000",
		"Population": "140702000",
		"Continent": "EU"
	},
	{
		"alpha2": "RW",
		"alpha3": "RWA",
		"numeric": "646",
		"fips": "RW",
		"Country": "Rwanda",
		"Capital": "Kigali",
		"Area in km²": "26338",
		"Population": "11055976",
		"Continent": "AF"
	},
	{
		"alpha2": "SA",
		"alpha3": "SAU",
		"numeric": "682",
		"fips": "SA",
		"Country": "Saudi Arabia",
		"Capital": "Riyadh",
		"Area in km²": "1960582",
		"Population": "25731776",
		"Continent": "AS"
	},
	{
		"alpha2": "SB",
		"alpha3": "SLB",
		"numeric": "90",
		"fips": "BP",
		"Country": "Solomon Islands",
		"Capital": "Honiara",
		"Area in km²": "28450",
		"Population": "559198",
		"Continent": "OC"
	},
	{
		"alpha2": "SC",
		"alpha3": "SYC",
		"numeric": "690",
		"fips": "SE",
		"Country": "Seychelles",
		"Capital": "Victoria",
		"Area in km²": "455",
		"Population": "88340",
		"Continent": "AF"
	},
	{
		"alpha2": "SD",
		"alpha3": "SDN",
		"numeric": "729",
		"fips": "SU",
		"Country": "Sudan",
		"Capital": "Khartoum",
		"Area in km²": "1861484",
		"Population": "35000000",
		"Continent": "AF"
	},
	{
		"alpha2": "SE",
		"alpha3": "SWE",
		"numeric": "752",
		"fips": "SW",
		"Country": "Sweden",
		"Capital": "Stockholm",
		"Area in km²": "449964",
		"Population": "9555893",
		"Continent": "EU"
	},
	{
		"alpha2": "SG",
		"alpha3": "SGP",
		"numeric": "702",
		"fips": "SN",
		"Country": "Singapore",
		"Capital": "Singapur",
		"Area in km²": "692.7",
		"Population": "4701069",
		"Continent": "AS"
	},
	{
		"alpha2": "SH",
		"alpha3": "SHN",
		"numeric": "654",
		"fips": "SH",
		"Country": "Saint Helena",
		"Capital": "Jamestown",
		"Area in km²": "410",
		"Population": "7460",
		"Continent": "AF"
	},
	{
		"alpha2": "SI",
		"alpha3": "SVN",
		"numeric": "705",
		"fips": "SI",
		"Country": "Slovenia",
		"Capital": "Ljubljana",
		"Area in km²": "20273",
		"Population": "2007000",
		"Continent": "EU"
	},
	{
		"alpha2": "SJ",
		"alpha3": "SJM",
		"numeric": "744",
		"fips": "SV",
		"Country": "Svalbard and Jan Mayen",
		"Capital": "Longyearbyen",
		"Area in km²": "62049",
		"Population": "2550",
		"Continent": "EU"
	},
	{
		"alpha2": "SK",
		"alpha3": "SVK",
		"numeric": "703",
		"fips": "LO",
		"Country": "Slovakia",
		"Capital": "Bratislava",
		"Area in km²": "48845",
		"Population": "5455000",
		"Continent": "EU"
	},
	{
		"alpha2": "SL",
		"alpha3": "SLE",
		"numeric": "694",
		"fips": "SL",
		"Country": "Sierra Leone",
		"Capital": "Freetown",
		"Area in km²": "71740",
		"Population": "5245695",
		"Continent": "AF"
	},
	{
		"alpha2": "SM",
		"alpha3": "SMR",
		"numeric": "674",
		"fips": "SM",
		"Country": "San Marino",
		"Capital": "San Marino",
		"Area in km²": "61.2",
		"Population": "31477",
		"Continent": "EU"
	},
	{
		"alpha2": "SN",
		"alpha3": "SEN",
		"numeric": "686",
		"fips": "SG",
		"Country": "Senegal",
		"Capital": "Dakar",
		"Area in km²": "196190",
		"Population": "12323252",
		"Continent": "AF"
	},
	{
		"alpha2": "SO",
		"alpha3": "SOM",
		"numeric": "706",
		"fips": "SO",
		"Country": "Somalia",
		"Capital": "Mogadishu",
		"Area in km²": "637657",
		"Population": "10112453",
		"Continent": "AF"
	},
	{
		"alpha2": "SR",
		"alpha3": "SUR",
		"numeric": "740",
		"fips": "NS",
		"Country": "Suriname",
		"Capital": "Paramaribo",
		"Area in km²": "163270",
		"Population": "492829",
		"Continent": "SA"
	},
	{
		"alpha2": "SS",
		"alpha3": "SSD",
		"numeric": "728",
		"fips": "OD",
		"Country": "South Sudan",
		"Capital": "Juba",
		"Area in km²": "644329",
		"Population": "8260490",
		"Continent": "AF"
	},
	{
		"alpha2": "ST",
		"alpha3": "STP",
		"numeric": "678",
		"fips": "TP",
		"Country": "São Tomé and Príncipe",
		"Capital": "Sao Tome",
		"Area in km²": "1001",
		"Population": "175808",
		"Continent": "AF"
	},
	{
		"alpha2": "SV",
		"alpha3": "SLV",
		"numeric": "222",
		"fips": "ES",
		"Country": "El Salvador",
		"Capital": "San Salvador",
		"Area in km²": "21040",
		"Population": "6052064",
		"Continent": "NA"
	},
	{
		"alpha2": "SX",
		"alpha3": "SXM",
		"numeric": "534",
		"fips": "NN",
		"Country": "Sint Maarten",
		"Capital": "Philipsburg",
		"Area in km²": "",
		"Population": "37429",
		"Continent": "NA"
	},
	{
		"alpha2": "SY",
		"alpha3": "SYR",
		"numeric": "760",
		"fips": "SY",
		"Country": "Syria",
		"Capital": "Damascus",
		"Area in km²": "185180",
		"Population": "22198110",
		"Continent": "AS"
	},
	{
		"alpha2": "SZ",
		"alpha3": "SWZ",
		"numeric": "748",
		"fips": "WZ",
		"Country": "Swaziland",
		"Capital": "Mbabane",
		"Area in km²": "17363",
		"Population": "1354051",
		"Continent": "AF"
	},
	{
		"alpha2": "TC",
		"alpha3": "TCA",
		"numeric": "796",
		"fips": "TK",
		"Country": "Turks and Caicos Islands",
		"Capital": "Cockburn Town",
		"Area in km²": "430",
		"Population": "20556",
		"Continent": "NA"
	},
	{
		"alpha2": "TD",
		"alpha3": "TCD",
		"numeric": "148",
		"fips": "CD",
		"Country": "Chad",
		"Capital": "N'Djamena",
		"Area in km²": "1284000",
		"Population": "10543464",
		"Continent": "AF"
	},
	{
		"alpha2": "TF",
		"alpha3": "ATF",
		"numeric": "260",
		"fips": "FS",
		"Country": "French Southern Territories",
		"Capital": "Port-aux-Francais",
		"Area in km²": "7829",
		"Population": "140",
		"Continent": "AN"
	},
	{
		"alpha2": "TG",
		"alpha3": "TGO",
		"numeric": "768",
		"fips": "TO",
		"Country": "Togo",
		"Capital": "Lome",
		"Area in km²": "56785",
		"Population": "6587239",
		"Continent": "AF"
	},
	{
		"alpha2": "TH",
		"alpha3": "THA",
		"numeric": "764",
		"fips": "TH",
		"Country": "Thailand",
		"Capital": "Bangkok",
		"Area in km²": "514000",
		"Population": "67089500",
		"Continent": "AS"
	},
	{
		"alpha2": "TJ",
		"alpha3": "TJK",
		"numeric": "762",
		"fips": "TI",
		"Country": "Tajikistan",
		"Capital": "Dushanbe",
		"Area in km²": "143100",
		"Population": "7487489",
		"Continent": "AS"
	},
	{
		"alpha2": "TK",
		"alpha3": "TKL",
		"numeric": "772",
		"fips": "TL",
		"Country": "Tokelau",
		"Capital": "",
		"Area in km²": "10",
		"Population": "1466",
		"Continent": "OC"
	},
	{
		"alpha2": "TL",
		"alpha3": "TLS",
		"numeric": "626",
		"fips": "TT",
		"Country": "East Timor",
		"Capital": "Dili",
		"Area in km²": "15007",
		"Population": "1154625",
		"Continent": "OC"
	},
	{
		"alpha2": "TM",
		"alpha3": "TKM",
		"numeric": "795",
		"fips": "TX",
		"Country": "Turkmenistan",
		"Capital": "Ashgabat",
		"Area in km²": "488100",
		"Population": "4940916",
		"Continent": "AS"
	},
	{
		"alpha2": "TN",
		"alpha3": "TUN",
		"numeric": "788",
		"fips": "TS",
		"Country": "Tunisia",
		"Capital": "Tunis",
		"Area in km²": "163610",
		"Population": "10589025",
		"Continent": "AF"
	},
	{
		"alpha2": "TO",
		"alpha3": "TON",
		"numeric": "776",
		"fips": "TN",
		"Country": "Tonga",
		"Capital": "Nuku'alofa",
		"Area in km²": "748",
		"Population": "122580",
		"Continent": "OC"
	},
	{
		"alpha2": "TR",
		"alpha3": "TUR",
		"numeric": "792",
		"fips": "TU",
		"Country": "Turkey",
		"Capital": "Ankara",
		"Area in km²": "780580",
		"Population": "77804122",
		"Continent": "AS"
	},
	{
		"alpha2": "TT",
		"alpha3": "TTO",
		"numeric": "780",
		"fips": "TD",
		"Country": "Trinidad and Tobago",
		"Capital": "Port of Spain",
		"Area in km²": "5128",
		"Population": "1228691",
		"Continent": "NA"
	},
	{
		"alpha2": "TV",
		"alpha3": "TUV",
		"numeric": "798",
		"fips": "TV",
		"Country": "Tuvalu",
		"Capital": "Funafuti",
		"Area in km²": "26",
		"Population": "10472",
		"Continent": "OC"
	},
	{
		"alpha2": "TW",
		"alpha3": "TWN",
		"numeric": "158",
		"fips": "TW",
		"Country": "Taiwan",
		"Capital": "Taipei",
		"Area in km²": "35980",
		"Population": "22894384",
		"Continent": "AS"
	},
	{
		"alpha2": "TZ",
		"alpha3": "TZA",
		"numeric": "834",
		"fips": "TZ",
		"Country": "Tanzania",
		"Capital": "Dodoma",
		"Area in km²": "945087",
		"Population": "41892895",
		"Continent": "AF"
	},
	{
		"alpha2": "UA",
		"alpha3": "UKR",
		"numeric": "804",
		"fips": "UP",
		"Country": "Ukraine",
		"Capital": "Kiev",
		"Area in km²": "603700",
		"Population": "45415596",
		"Continent": "EU"
	},
	{
		"alpha2": "UG",
		"alpha3": "UGA",
		"numeric": "800",
		"fips": "UG",
		"Country": "Uganda",
		"Capital": "Kampala",
		"Area in km²": "236040",
		"Population": "33398682",
		"Continent": "AF"
	},
	{
		"alpha2": "UM",
		"alpha3": "UMI",
		"numeric": "581",
		"fips": "",
		"Country": "U.S. Minor Outlying Islands",
		"Capital": "",
		"Area in km²": "0",
		"Population": "0",
		"Continent": "OC"
	},
	{
		"alpha2": "US",
		"alpha3": "USA",
		"numeric": "840",
		"fips": "US",
		"Country": "United States",
		"Capital": "Washington",
		"Area in km²": "9629091",
		"Population": "310232863",
		"Continent": "NA"
	},
	{
		"alpha2": "UY",
		"alpha3": "URY",
		"numeric": "858",
		"fips": "UY",
		"Country": "Uruguay",
		"Capital": "Montevideo",
		"Area in km²": "176220",
		"Population": "3477000",
		"Continent": "SA"
	},
	{
		"alpha2": "UZ",
		"alpha3": "UZB",
		"numeric": "860",
		"fips": "UZ",
		"Country": "Uzbekistan",
		"Capital": "Tashkent",
		"Area in km²": "447400",
		"Population": "27865738",
		"Continent": "AS"
	},
	{
		"alpha2": "VA",
		"alpha3": "VAT",
		"numeric": "336",
		"fips": "VT",
		"Country": "Vatican City",
		"Capital": "Vatican City",
		"Area in km²": "0.4",
		"Population": "921",
		"Continent": "EU"
	},
	{
		"alpha2": "VC",
		"alpha3": "VCT",
		"numeric": "670",
		"fips": "VC",
		"Country": "Saint Vincent and the Grenadines",
		"Capital": "Kingstown",
		"Area in km²": "389",
		"Population": "104217",
		"Continent": "NA"
	},
	{
		"alpha2": "VE",
		"alpha3": "VEN",
		"numeric": "862",
		"fips": "VE",
		"Country": "Venezuela",
		"Capital": "Caracas",
		"Area in km²": "912050",
		"Population": "27223228",
		"Continent": "SA"
	},
	{
		"alpha2": "VG",
		"alpha3": "VGB",
		"numeric": "92",
		"fips": "VI",
		"Country": "British Virgin Islands",
		"Capital": "Road Town",
		"Area in km²": "153",
		"Population": "21730",
		"Continent": "NA"
	},
	{
		"alpha2": "VI",
		"alpha3": "VIR",
		"numeric": "850",
		"fips": "VQ",
		"Country": "U.S. Virgin Islands",
		"Capital": "Charlotte Amalie",
		"Area in km²": "352",
		"Population": "108708",
		"Continent": "NA"
	},
	{
		"alpha2": "VN",
		"alpha3": "VNM",
		"numeric": "704",
		"fips": "VM",
		"Country": "Vietnam",
		"Capital": "Hanoi",
		"Area in km²": "329560",
		"Population": "89571130",
		"Continent": "AS"
	},
	{
		"alpha2": "VU",
		"alpha3": "VUT",
		"numeric": "548",
		"fips": "NH",
		"Country": "Vanuatu",
		"Capital": "Port Vila",
		"Area in km²": "12200",
		"Population": "221552",
		"Continent": "OC"
	},
	{
		"alpha2": "WF",
		"alpha3": "WLF",
		"numeric": "876",
		"fips": "WF",
		"Country": "Wallis and Futuna",
		"Capital": "Mata Utu",
		"Area in km²": "274",
		"Population": "16025",
		"Continent": "OC"
	},
	{
		"alpha2": "WS",
		"alpha3": "WSM",
		"numeric": "882",
		"fips": "WS",
		"Country": "Samoa",
		"Capital": "Apia",
		"Area in km²": "2944",
		"Population": "192001",
		"Continent": "OC"
	},
	{
		"alpha2": "XK",
		"alpha3": "XKX",
		"numeric": "0",
		"fips": "KV",
		"Country": "Kosovo",
		"Capital": "Pristina",
		"Area in km²": "",
		"Population": "1800000",
		"Continent": "EU"
	},
	{
		"alpha2": "YE",
		"alpha3": "YEM",
		"numeric": "887",
		"fips": "YM",
		"Country": "Yemen",
		"Capital": "Sanaa",
		"Area in km²": "527970",
		"Population": "23495361",
		"Continent": "AS"
	},
	{
		"alpha2": "YT",
		"alpha3": "MYT",
		"numeric": "175",
		"fips": "MF",
		"Country": "Mayotte",
		"Capital": "Mamoudzou",
		"Area in km²": "374",
		"Population": "159042",
		"Continent": "AF"
	},
	{
		"alpha2": "ZA",
		"alpha3": "ZAF",
		"numeric": "710",
		"fips": "SF",
		"Country": "South Africa",
		"Capital": "Pretoria",
		"Area in km²": "1219912",
		"Population": "49000000",
		"Continent": "AF"
	},
	{
		"alpha2": "ZM",
		"alpha3": "ZMB",
		"numeric": "894",
		"fips": "ZA",
		"Country": "Zambia",
		"Capital": "Lusaka",
		"Area in km²": "752614",
		"Population": "13460305",
		"Continent": "AF"
	},
	{
		"alpha2": "ZW",
		"alpha3": "ZWE",
		"numeric": "716",
		"fips": "ZI",
		"Country": "Zimbabwe",
		"Capital": "Harare",
		"Area in km²": "390580",
		"Population": "11651858",
		"Continent": "AF"
	}
];